import { GalleryItem, CategoryFilter } from "./types";

export const GALLERY_CATEGORIES: CategoryFilter[] = [
  {
    id: "all",
    label: "सम्पूर्ण दर्शन",
    subLabel: "All Gallery",
    count: 18,
  },
  {
    id: "darshan",
    label: "दिव्य स्वरूप",
    subLabel: "Divine Deity",
    count: 4,
  },
  {
    id: "mandir",
    label: "मंदिर परिसर",
    subLabel: "Dham Architecture",
    count: 6,
  },
  {
    id: "anushthan",
    label: "महायज्ञ व अनुष्ठान",
    subLabel: "Hawan & Yajna",
    count: 3,
  },
  {
    id: "pujan",
    label: "विशेष निवारण पूजा",
    subLabel: "Special Pujas",
    count: 4,
  },
  {
    id: "ratrideep",
    label: "रात्रि दीप दर्शन",
    subLabel: "Night Illumination",
    count: 1,
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "panoramic-temple-view",
    title: "माँ बगलामुखी मंदिर विस्तृत विहंगम दर्शन",
    subtitle: "सिद्ध शक्तिपीठ नलखेड़ा धाम का संपूर्ण पावन परिसर",
    category: "mandir",
    categoryLabel: "मंदिर परिसर",
    image: "/mandir/mandir-complex-panoramic.jpg",
    aspect: "panoramic",
    spanType: "featured",
    badge: "॥ ॐ ॥ महाशक्तिपीठ",
    caption:
      "विश्व प्रसिद्ध माँ बगलामुखी नलखेड़ा धाम (आगर मालवा, म.प्र.) का भव्य एवं दिव्य विहंगम दृश्य। यहाँ लाखों भक्त अपनी मनोकामनाओं एवं विजय प्राप्ति हेतु दर्शन लाभ प्राप्त करते हैं।",
    mantra: "ॐ ह्रीं बगलामुखी सर्वदुष्टानां वाचं मुखं पदं स्तम्भय जिह्वां कीलय बुद्धिं विनाशय ह्रीं ॐ स्वाहा।",
    location: "नलखेड़ा धाम, आगर मालवा",
  },
  {
    id: "divine-darshan-mata",
    title: "माँ पीताम्बरा बगलामुखी दिव्य स्वरूप",
    subtitle: "स्वर्ण श्रृंगार एवं पावन गर्भगृह दर्शन",
    category: "darshan",
    categoryLabel: "दिव्य स्वरूप",
    image: "/mandir/baglamukhi-divine-darshan.jpg",
    aspect: "portrait",
    spanType: "tall",
    badge: "✦ स्वयंभू शक्तिपीठ",
    caption:
      "माता बगलामुखी का परम तेजस्वी चतुर्भुज दिव्य विग्रह, जहाँ माँ के दर्शन मात्र से समस्त भय, व्याधि, शत्रु संकट एवं ग्रह दोष तत्काल भस्म हो जाते हैं।",
    mantra: "जिह्वाग्रमादाय करेण देवीं, पीताम्बराढ्यां द्विभुजां त्रिनेत्राम्।",
    location: "गर्भगृह, नलखेड़ा",
  },
  {
    id: "night-golden-darshan",
    title: "स्वर्णिम दीप प्रकाश रात्रि दर्शन",
    subtitle: "संध्या महाआरती के उपरांत मंदिर की अलौकिक आभा",
    category: "ratrideep",
    categoryLabel: "रात्रि दीप दर्शन",
    image: "/mandir/mandir-night-darshan.jpg",
    aspect: "landscape",
    spanType: "wide",
    badge: "॥ अखंड दीप दर्शन ॥",
    caption:
      "संध्या काल में दिव्य दीपों एवं स्वर्णिम प्रकाश से आलोकित माँ बगलामुखी मंदिर। लखुंदर नदी के पावन तट पर रात्रि में अलौकिक आध्यात्मिक शांति का अनुभव होता है।",
    mantra: "दीपज्योतिः परब्रह्म दीपज्योतिर्जनार्दनः। दीपो हरतु मे पापं दीपज्योतिर्नमोऽस्तु ते॥",
    location: "मंदिर प्रांगण, नलखेड़ा",
  },
  {
    id: "maha-hawan-yajna",
    title: "वैदिक महाहवन एवं पीताम्बरा आहुति",
    subtitle: "अखंड अग्नि कुंड में 1008 महामंत्रों की आहुति",
    category: "anushthan",
    categoryLabel: "महायज्ञ व अनुष्ठान",
    image: "/mandir/baglamukhi-maha-hawan.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "॥ महाहवन ॥",
    caption:
      "पीले पुष्प, तिल, राई एवं विशेष वैदिक औषधियों से संपन्न माँ बगलामुखी का महाहवन। समस्त नकारात्मक ऊर्जा, नजर दोष एवं तांत्रिक बाधाओं का पूर्ण शमन।",
    mantra: "ॐ ऐं ह्रीं श्रीं क्लीं पीताम्बरायै नमः स्वाहा।",
    location: "यज्ञशाला, नलखेड़ा धाम",
  },
  {
    id: "siddha-anusthan-vidhi",
    title: "36,000 व सवा लाख मंत्र सिद्ध अनुष्ठान",
    subtitle: "पंडित शुभम शर्मा जी के सान्निध्य में संकल्पित साधना",
    category: "anushthan",
    categoryLabel: "महायज्ञ व अनुष्ठान",
    image: "/mandir/baglamukhi-siddha-anusthan.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "॥ सिद्ध अनुष्ठान ॥",
    caption:
      "शास्त्रोक्त विधि-विधान से ब्राह्मणों द्वारा 11 दिवसीय अथवा 21 दिवसीय अखंड मंत्र जाप अनुष्ठान, जिससे जीवन में असंभव कार्य भी सुगम हो जाते हैं।",
    mantra: "ॐ ह्लीं क्लीं ह्लीं बगलामुख्यै नमः।",
    location: "अनुष्ठान मंडप",
  },
  {
    id: "mantra-jaap-sadhna",
    title: "हल्दी माला से पीताम्बरा मंत्र जप साधना",
    subtitle: "विशेष एकाग्रता एवं तांत्रिक शुद्धि विधान",
    category: "anushthan",
    categoryLabel: "महायज्ञ व अनुष्ठान",
    image: "/mandir/baglamukhi-mantra-jaap.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "॥ मंत्र साधना ॥",
    caption:
      "शुद्ध हल्दी की माला पर बगलामुखी महाविद्या मंत्र का जाप। यह साधना जातक के जीवन में वाक-सिद्धि, आत्मबल और विजय मार्ग को प्रशस्त करती है।",
    mantra: "ॐ ह्रीं ॐ ऐं क्लीं सौः सौः बगलामुखी देव्यै नमः।",
    location: "साधना कक्ष",
  },
  {
    id: "mandir-main-facade",
    title: "माँ बगलामुखी मुख्य शिखर एवं प्रांगण",
    subtitle: "प्राचीन वास्तुकला एवं पावन परिक्रमा मार्ग",
    category: "mandir",
    categoryLabel: "मंदिर परिसर",
    image: "/mandir/mandir-main-facade.jpg",
    aspect: "landscape",
    spanType: "wide",
    badge: "॥ मुख्य शिखर ॥",
    caption:
      "महाभारत कालीन ऐतिहासिक एवं पौराणिक महत्ता से सुशोभित माँ बगलामुखी मंदिर का मुख्य शिखर एवं भव्य परिक्रमा मार्ग।",
    mantra: "सर्वमंगल मांगल्ये शिवे सर्वार्थ साधिके। शरण्ये त्र्यम्बके गौरी नारायणि नमोऽस्तु ते॥",
    location: "नलखेड़ा धाम",
  },
  {
    id: "puja-shatru-raksha",
    title: "शत्रु बाधा निवारण एवं कानूनी विजय पूजा",
    subtitle: "अदृश्य विरोधियों व कोर्ट-कचहरी में सुरक्षा हेतु",
    category: "pujan",
    categoryLabel: "विशेष निवारण पूजा",
    image: "/mandir/puja-shatru-raksha.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "॥ विजय संकल्प ॥",
    caption:
      "विरोधी स्तंभन एवं विजय प्राप्ति हेतु विशेष तांत्रिक पूजा। झूठे मुकदमों, षड्यंत्रों एवं ईर्ष्या से स्थायी सुरक्षा प्रदान करती है।",
    mantra: "शत्रु नाशय नाशय, वाचं मुखं पदं स्तम्भय ह्रीं स्वाहा।",
    location: "सिद्ध पूजा पीठ",
  },
  {
    id: "puja-vittiya-samriddhi",
    title: "ऋण मुक्ति एवं आर्थिक स्थिरता अनुष्ठान",
    subtitle: "धन हानि, कर्ज निवारण एवं व्यापारिक संकट मुक्ति",
    category: "pujan",
    categoryLabel: "विशेष निवारण पूजा",
    image: "/mandir/puja-vittiya-samriddhi.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "॥ धन-वैभव योग ॥",
    caption:
      "अचानक होने वाली आर्थिक हानि, रुके हुए धन की प्राप्ति तथा व्यापार में लगातार घाटे से मुक्ति के लिए श्री सूक्त एवं बगलामुखी संयुक्त अनुष्ठान।",
    mantra: "ॐ श्रीं ह्रीं क्लीं त्रिभुवन महालक्ष्म्यै अस्माकं दारिद्र्यं नाशय नाशय स्वाहा।",
    location: "पूजा पीठ, नलखेड़ा",
  },
  {
    id: "puja-vyapar-vriddhi",
    title: "व्यापार विस्तार एवं करियर उन्नति महापूजा",
    subtitle: "नई योजनाओं में सफलता एवं प्रतिष्ठा वृद्धि",
    category: "pujan",
    categoryLabel: "विशेष निवारण पूजा",
    image: "/mandir/puja-vyapar-vriddhi.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "॥ व्यापार उन्नति ॥",
    caption:
      "व्यापार, उद्योग, राजनीति एवं उच्च पद प्राप्ति के मार्ग में आने वाली बाधाओं के शमन हेतु विशेष पीताम्बरा हवन एवं संकल्प।",
    mantra: "ॐ ह्रीं श्रीं बगलामुखी सर्व सिद्धिं देहि देहि नमः।",
    location: "नलखेड़ा धाम",
  },
  {
    id: "puja-swasthya-samriddhi",
    title: "आरोग्य, सुख एवं ऐश्वर्य प्राप्ति पूजा",
    subtitle: "दीर्घायु, मानसिक शांति एवं पारिवारिक सौहार्द",
    category: "pujan",
    categoryLabel: "विशेष निवारण पूजा",
    image: "/mandir/puja-swasthya-samriddhi.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "॥ महाआरोग्य ॥",
    caption:
      "असाध्य रोगों, अकाल मृत्यु भय, नकारात्मक साए एवं पारिवारिक क्लेश से मुक्ति हेतु महामृत्युंजय एवं बगलामुखी विशेष कवच पूजा।",
    mantra: "ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्। उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय माऽमृतात्॥",
    location: "नलखेड़ा धाम",
  },
  {
    id: "temple-view-courtyard",
    title: "मंदिर मुख्य प्रांगण एवं भक्त दर्शन मार्ग",
    subtitle: "पावन शांत वातावरण एवं परिक्रमा क्षेत्र",
    category: "mandir",
    categoryLabel: "मंदिर परिसर",
    image: "/mandir/temple-view-courtyard.jpg",
    aspect: "landscape",
    spanType: "wide",
    badge: "॥ पावन प्रांगण ॥",
    caption:
      "भक्तों के दर्शन, विश्राम एवं भजन-कीर्तन हेतु सुंदर एवं सुव्यवस्थित मंदिर प्रांगण, जहाँ सदैव माँ की कृपा की अनुभूति होती है।",
    mantra: "आनन्दमानन्दकरं प्रसन्नं ज्ञानस्वरूपं निजबोधयुक्तम्।",
    location: "परिसर, नलखेड़ा",
  },
  {
    id: "temple-view-sanctum",
    title: "गर्भगृह बाह्य द्वार एवं स्वर्ण कलश दर्शन",
    subtitle: "मंदिर के मुख्य शिखर पर स्थापित पावन ध्वज व कलश",
    category: "mandir",
    categoryLabel: "मंदिर परिसर",
    image: "/mandir/temple-view-sanctum.jpg",
    aspect: "portrait",
    spanType: "tall",
    badge: "॥ स्वर्ण कलश ॥",
    caption:
      "मंदिर के शीर्ष पर स्थापित दिव्य स्वर्ण कलश एवं ध्वज, जो मीलों दूर से ही भक्तों को माँ के पावन सान्निध्य का संदेश देता है।",
    mantra: "जयति जयति जगन्माता बगलामुखी नमो नमः।",
    location: "शिखर दर्शन",
  },
  {
    id: "temple-view-gateway",
    title: "मंदिर का भव्य मुख्य तोरण द्वार",
    subtitle: "नलखेड़ा धाम में श्रद्धालुओं का प्रथम प्रवेश मार्ग",
    category: "mandir",
    categoryLabel: "मंदिर परिसर",
    image: "/mandir/temple-view-gateway.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "॥ मुख्य प्रवेश द्वार ॥",
    caption:
      "नलखेड़ा धाम में माँ बगलामुखी के दर्शन हेतु पहुँचने वाले श्रद्धालुओं का स्वागत करता भव्य एवं पावन तोरण द्वार।",
    mantra: "प्रविश्य नगर कीजे सब काजा। हृदय राखि कौसलपुर राजा॥",
    location: "प्रवेश द्वार, नलखेड़ा",
  },
  {
    id: "temple-view-front",
    title: "अग्रभाग से मंदिर का सुंदर नयनाभिराम दृश्य",
    subtitle: "सूर्योदय कालीन प्रातः आरती का दृश्य",
    category: "mandir",
    categoryLabel: "मंदिर परिसर",
    image: "/mandir/temple-view-front.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "॥ प्रातः दर्शन ॥",
    caption:
      "प्रातः काल सूर्य की प्रथम किरणों के साथ माँ बगलामुखी मंदिर का स्वर्णमयी आभा से चमकता अग्रभाग।",
    mantra: "प्रातः स्मरामि भवभीतिहरं सुरेशं वन्दारु वृन्दारक मन्दारम्।",
    location: "नलखेड़ा धाम",
  },
  {
    id: "temple-view-side",
    title: "मंदिर का पार्श्व स्थापत्य एवं प्राचीन दीवारें",
    subtitle: "त्रिशूल एवं चक्र चिन्हों से सुसज्जित प्राचीन भित्तियां",
    category: "mandir",
    categoryLabel: "मंदिर परिसर",
    image: "/mandir/temple-view-side.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "॥ प्राचीन स्थापत्य ॥",
    caption:
      "सिद्ध पीठ की प्राचीन वास्तुकला एवं परिक्रमा मार्ग की ऐतिहासिक दीवारें, जो सदियों की साधना की साक्षी हैं।",
    mantra: "ॐ ह्रीं क्लीं बगलामुख्यै नमः।",
    location: "पार्श्व भाग, नलखेड़ा",
  },
  {
    id: "mandir-history-view",
    title: "प्राचीन बगलामुखी महापीठ ऐतिहासिक दृश्य",
    subtitle: "महाभारत कालीन सिद्ध पीठ की गौरवशाली गाथा",
    category: "darshan",
    categoryLabel: "दिव्य स्वरूप",
    image: "/mandir/mandir-history.jpg",
    aspect: "portrait",
    spanType: "normal",
    badge: "॥ ऐतिहासिक पीठ ॥",
    caption:
      "कहा जाता है कि महाभारत युद्ध में विजय प्राप्ति हेतु भगवान श्रीकृष्ण के निर्देश पर धर्मराज युधिष्ठिर ने इस पीठ पर माँ बगलामुखी की आराधना की थी।",
    mantra: "यतो धर्मस्ततो जयः।",
    location: "ऐतिहासिक अभिलेख",
  },
  {
    id: "mandir-entry-illustration",
    title: "माँ बगलामुखी मंदिर भव्य प्रवेश तोरण",
    subtitle: "पवित्र द्वार दर्शन एवं शुभ शंखनाद",
    category: "darshan",
    categoryLabel: "दिव्य स्वरूप",
    image: "/mandir/enteryGate.png",
    aspect: "portrait",
    spanType: "normal",
    badge: "॥ मंगल प्रवेश ॥",
    caption:
      "माँ के दरबार में प्रवेश करते ही मन को अपार शांति और शक्ति का अनुभव होता है। समस्त विघ्न दूर होते हैं।",
    mantra: "ॐ गं गणपतये नमः। ॐ बगलामुख्यै नमः।",
    location: "मुख्य तोरण",
  },
];
