import { GalleryItem, CategoryFilter } from "./types";

export const GALLERY_CATEGORIES: CategoryFilter[] = [
  {
    id: "all",
    label: "All Darshan",
    subLabel: "सम्पूर्ण दर्शन",
    count: 18,
  },
  {
    id: "darshan",
    label: "Divine Deity",
    subLabel: "दिव्य स्वरूप",
    count: 4,
  },
  {
    id: "mandir",
    label: "Temple Complex",
    subLabel: "मंदिर परिसर",
    count: 6,
  },
  {
    id: "anushthan",
    label: "Hawan & Yajna",
    subLabel: "महायज्ञ व अनुष्ठान",
    count: 3,
  },
  {
    id: "pujan",
    label: "Special Pujas",
    subLabel: "विशेष निवारण पूजा",
    count: 4,
  },
  {
    id: "ratrideep",
    label: "Night Illumination",
    subLabel: "रात्रि दीप दर्शन",
    count: 1,
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "panoramic-temple-view",
    title: "Maa Baglamukhi Temple Panoramic Darshan",
    subtitle: "Sacred Peeth Complex at Nalkheda Dham",
    category: "mandir",
    categoryLabel: "Temple Complex",
    image: "/mandir/mandir-complex-panoramic.jpg",
    aspect: "panoramic",
    spanType: "featured",
    badge: "Maha Shaktipeeth",
    caption:
      "विश्व प्रसिद्ध माँ बगलामुखी नलखेड़ा धाम (आगर मालवा, म.प्र.) का भव्य एवं दिव्य विहंगम दृश्य। यहाँ लाखों भक्त अपनी मनोकामनाओं एवं विजय प्राप्ति हेतु दर्शन लाभ प्राप्त करते हैं।",
    mantra: "ॐ ह्रीं बगलामुखी सर्वदुष्टानां वाचं मुखं पदं स्तम्भय जिह्वां कीलय बुद्धिं विनाशय ह्रीं ॐ स्वाहा।",
    location: "Nalkheda Dham, Agar Malwa",
  },
  {
    id: "divine-darshan-mata",
    title: "Divine Deity Form of Maa Pitambara",
    subtitle: "Golden Shringar & Sanctum Sanctorum",
    category: "darshan",
    categoryLabel: "Divine Deity",
    image: "/mandir/baglamukhi-divine-darshan.jpg",
    aspect: "portrait",
    spanType: "tall",
    badge: "Swayambhu Peeth",
    caption:
      "माता बगलामुखी का परम तेजस्वी चतुर्भुज दिव्य विग्रह, जहाँ माँ के दर्शन मात्र से समस्त भय, व्याधि, शत्रु संकट एवं ग्रह दोष तत्काल भस्म हो जाते हैं।",
    mantra: "जिह्वाग्रमादाय करेण देवीं, पीताम्बराढ्यां द्विभुजां त्रिनेत्राम्।",
    location: "Garbhagriha, Nalkheda",
  },
  {
    id: "night-golden-darshan",
    title: "Golden Deepotsav Night Illumination",
    subtitle: "Divine Aura After Evening Maha Aarti",
    category: "ratrideep",
    categoryLabel: "Night Illumination",
    image: "/mandir/mandir-night-darshan.jpg",
    aspect: "landscape",
    spanType: "wide",
    badge: "Akhand Deep",
    caption:
      "संध्या काल में दिव्य दीपों एवं स्वर्णिम प्रकाश से आलोकित माँ बगलामुखी मंदिर। लखुंदर नदी के पावन तट पर रात्रि में अलौकिक आध्यात्मिक शांति का अनुभव होता है।",
    mantra: "दीपज्योतिः परब्रह्म दीपज्योतिर्जनार्दनः। दीपो हरतु मे पापं दीपज्योतिर्नमोऽस्तु ते॥",
    location: "Temple Courtyard, Nalkheda",
  },
  {
    id: "maha-hawan-yajna",
    title: "Maa Baglamukhi 56 Bhog & Maha Prasad",
    subtitle: "Divine Offerings on Auspicious Yajna & Festivals",
    category: "anushthan",
    categoryLabel: "Hawan & Yajna",
    image: "/mandir/56bhog.png",
    aspect: "landscape",
    spanType: "normal",
    badge: "56 Bhog",
    caption:
      "माता पीताम्बरा को अर्पित 56 भोग एवं दिव्य नैवेद्य। माँ के पावन प्रसाद से समस्त पापों का नाश एवं सर्व सुख-समृद्धि की प्राप्ति होती है।",
    mantra: "ॐ ऐं ह्रीं श्रीं क्लीं पीताम्बरायै नमः स्वाहा।",
    location: "Yajnashala, Nalkheda Dham",
  },
  {
    id: "siddha-anusthan-vidhi",
    title: "36,000 & 125,000 Mantra Siddha Anushthan",
    subtitle: "Consecrated Sadhana Under Pujya Guruji Guidance",
    category: "anushthan",
    categoryLabel: "Hawan & Yajna",
    image: "/mandir/baglamukhi-siddha-anusthan.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "Siddha Anushthan",
    caption:
      "शास्त्रोक्त विधि-विधान से ब्राह्मणों द्वारा 11 दिवसीय अथवा 21 दिवसीय अखंड मंत्र जाप अनुष्ठान, जिससे जीवन में असंभव कार्य भी सुगम हो जाते हैं।",
    mantra: "ॐ ह्लीं क्लीं ह्लीं बगलामुख्यै नमः।",
    location: "Anushthan Mandap",
  },
  {
    id: "mantra-jaap-sadhna",
    title: "Sacred Parikrama & Mantra Japa Path",
    subtitle: "Spiritual Concentration & Tantric Purification",
    category: "anushthan",
    categoryLabel: "Hawan & Yajna",
    image: "/mandir/walkline.png",
    aspect: "landscape",
    spanType: "normal",
    badge: "Parikrama Path",
    caption:
      "माँ के मंदिर की पावन परिक्रमा एवं मंत्र जाप साधना। यह साधना जातक के जीवन में वाक-सिद्धि, आत्मबल और विजय मार्ग को प्रशस्त करती है।",
    mantra: "ॐ ह्रीं ॐ ऐं क्लीं सौः सौः बगलामुखी देव्यै नमः।",
    location: "Parikrama Pathway",
  },
  {
    id: "mandir-main-facade",
    title: "Maa Baglamukhi Main Shikhara & Courtyard",
    subtitle: "Ancient Vedic Architecture & Temple Sanctum",
    category: "mandir",
    categoryLabel: "Temple Complex",
    image: "/mandir/mandir-main-facade.jpg",
    aspect: "landscape",
    spanType: "wide",
    badge: "Main Shikhara",
    caption:
      "महाभारत कालीन ऐतिहासिक एवं पौराणिक महत्ता से सुशोभित माँ बगलामुखी मंदिर का मुख्य शिखर एवं भव्य परिक्रमा मार्ग।",
    mantra: "सर्वमंगल मांगल्ये शिवे सर्वार्थ साधिके। शरण्ये त्र्यम्बके गौरी नारायणि नमोऽस्तु ते॥",
    location: "Nalkheda Dham",
  },
  {
    id: "puja-shatru-raksha",
    title: "Shatru Badha Nivaran & Legal Victory Puja",
    subtitle: "Divine Protection Against Hidden Adversaries & Court Disputes",
    category: "pujan",
    categoryLabel: "Special Pujas",
    image: "/mandir/puja-shatru-raksha.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "Victory Sankalp",
    caption:
      "विरोधी स्तंभन एवं विजय प्राप्ति हेतु विशेष तांत्रिक पूजा। झूठे मुकदमों, षड्यंत्रों एवं ईर्ष्या से स्थायी सुरक्षा प्रदान करती है।",
    mantra: "शत्रु नाशय नाशय, वाचं मुखं पदं स्तम्भय ह्रीं स्वाहा।",
    location: "Siddha Puja Peeth",
  },
  {
    id: "puja-vittiya-samriddhi",
    title: "Rin Mukti & Financial Prosperity Anushthan",
    subtitle: "Relief from Debts, Financial Losses & Business Crises",
    category: "pujan",
    categoryLabel: "Special Pujas",
    image: "/mandir/puja-vittiya-samriddhi.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "Wealth & Prosperity",
    caption:
      "अचानक होने वाली आर्थिक हानि, रुके हुए धन की प्राप्ति तथा व्यापार में लगातार घाटे से मुक्ति के लिए श्री सूक्त एवं बगलामुखी संयुक्त अनुष्ठान।",
    mantra: "ॐ श्रीं ह्रीं क्लीं त्रिभुवन महालक्ष्म्यै अस्माकं दारिद्र्यं नाशय नाशय स्वाहा।",
    location: "Puja Peeth, Nalkheda",
  },
  {
    id: "puja-vyapar-vriddhi",
    title: "Vyapar Vriddhi & Business Growth Maha Puja",
    subtitle: "Success in Ventures, Trade Expansion & Career Growth",
    category: "pujan",
    categoryLabel: "Special Pujas",
    image: "/mandir/puja-vyapar-vriddhi.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "Business Growth",
    caption:
      "व्यापार, उद्योग, राजनीति एवं उच्च पद प्राप्ति के मार्ग में आने वाली बाधाओं के शमन हेतु विशेष पीताम्बरा हवन एवं संकल्प।",
    mantra: "ॐ ह्रीं श्रीं बगलामुखी सर्व सिद्धिं देहि देहि नमः।",
    location: "Nalkheda Dham",
  },
  {
    id: "puja-swasthya-samriddhi",
    title: "Arogya, Health & Divine Prosperity Puja",
    subtitle: "Longevity, Mental Peace & Harmonious Family Life",
    category: "pujan",
    categoryLabel: "Special Pujas",
    image: "/mandir/puja-swasthya-samriddhi.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "Maha Arogya",
    caption:
      "असाध्य रोगों, अकाल मृत्यु भय, नकारात्मक साए एवं पारिवारिक क्लेश से मुक्ति हेतु महामृत्युंजय एवं बगलामुखी विशेष कवच पूजा।",
    mantra: "ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्। उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय माऽमृतात्॥",
    location: "Nalkheda Dham",
  },
  {
    id: "temple-view-courtyard",
    title: "Temple Main Courtyard & Inner Sanctum Overview",
    subtitle: "Peaceful Spiritual Ambience & Devotee Gathering Area",
    category: "mandir",
    categoryLabel: "Temple Complex",
    image: "/mandir/mandirInsideOverview.png",
    aspect: "landscape",
    spanType: "wide",
    badge: "Sacred Courtyard",
    caption:
      "भक्तों के दर्शन, विश्राम एवं भजन-कीर्तन हेतु सुंदर एवं सुव्यवस्थित मंदिर प्रांगण, जहाँ सदैव माँ की कृपा की अनुभूति होती है।",
    mantra: "आनन्दमानन्दकरं प्रसन्नं ज्ञानस्वरूपं निजबोधयुक्तम्।",
    location: "Courtyard, Nalkheda",
  },
  {
    id: "temple-view-sanctum",
    title: "Sanctum Outer Gateway & Golden Kalash",
    subtitle: "Auspicious Temple Flag & Golden Shikhara Pinnacle",
    category: "mandir",
    categoryLabel: "Temple Complex",
    image: "/mandir/temple-view-sanctum.jpg",
    aspect: "portrait",
    spanType: "tall",
    badge: "Golden Kalash",
    caption:
      "मंदिर के शीर्ष पर स्थापित दिव्य स्वर्ण कलश एवं ध्वज, जो मीलों दूर से ही भक्तों को माँ के पावन सान्निध्य का संदेश देता है।",
    mantra: "जयति जयति जगन्माता बगलामुखी नमो नमः।",
    location: "Shikhara Darshan",
  },
  {
    id: "temple-view-gateway",
    title: "Grand Gateway & Simhadwar Entrance",
    subtitle: "Welcoming Devotees to Nalkheda Dham",
    category: "mandir",
    categoryLabel: "Temple Complex",
    image: "/mandir/gate.png",
    aspect: "landscape",
    spanType: "normal",
    badge: "Main Gateway",
    caption:
      "नलखेड़ा धाम में माँ बगलामुखी के दर्शन हेतु पहुँचने वाले श्रद्धालुओं का स्वागत करता भव्य एवं पावन तोरण द्वार।",
    mantra: "प्रविश्य नगर कीजे सब काजा। हृदय राखि कौसलपुर राजा॥",
    location: "Entrance Gate, Nalkheda",
  },
  {
    id: "temple-view-front",
    title: "Morning Sunrise Darshan & Front Facade",
    subtitle: "Golden Sunrise Aura Over The Sacred Sanctum",
    category: "mandir",
    categoryLabel: "Temple Complex",
    image: "/mandir/temple-view-front.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "Morning Darshan",
    caption:
      "प्रातः काल सूर्य की प्रथम किरणों के साथ माँ बगलामुखी मंदिर का स्वर्णमयी आभा से चमकता अग्रभाग।",
    mantra: "प्रातः स्मरामि भवभीतिहरं सुरेशं वन्दारु वृन्दारक मन्दारम्।",
    location: "Nalkheda Dham",
  },
  {
    id: "temple-view-side",
    title: "Historic Temple Architecture & Ancient Stone Walls",
    subtitle: "Sacred Symbols & Century-Old Vedic Craftsmanship",
    category: "mandir",
    categoryLabel: "Temple Complex",
    image: "/mandir/temple-view-side.jpg",
    aspect: "landscape",
    spanType: "normal",
    badge: "Ancient Architecture",
    caption:
      "सिद्ध पीठ की प्राचीन वास्तुकला एवं परिक्रमा मार्ग की ऐतिहासिक दीवारें, जो सदियों की साधना की साक्षी हैं।",
    mantra: "ॐ ह्रीं क्लीं बगलामुख्यै नमः।",
    location: "Side Facade, Nalkheda",
  },
  {
    id: "mandir-history-view",
    title: "Historical Mahabharata Era Siddha Peeth",
    subtitle: "Ancient Abode Established by Dharmaraj Yudhishthira",
    category: "darshan",
    categoryLabel: "Divine Deity",
    image: "/mandir/baglamukhi-siddha-anusthan.jpg",
    aspect: "portrait",
    spanType: "normal",
    badge: "Historic Peeth",
    caption:
      "कहा जाता है कि महाभारत युद्ध में विजय प्राप्ति हेतु भगवान श्रीकृष्ण के निर्देश पर धर्मराज युधिष्ठिर ने इस पीठ पर माँ बगलामुखी की आराधना की थी।",
    mantra: "यतो धर्मस्ततो जयः।",
    location: "Historical Archives",
  },
  {
    id: "mandir-entry-illustration",
    title: "Auspicious Grand Entrance Archway",
    subtitle: "Sacred Archway Darshan & Divine Conch Sounds",
    category: "darshan",
    categoryLabel: "Divine Deity",
    image: "/mandir/enteryGate.png",
    aspect: "portrait",
    spanType: "normal",
    badge: "Auspicious Entry",
    caption:
      "माँ के दरबार में प्रवेश करते ही मन को अपार शांति और शक्ति का अनुभव होता है। समस्त विघ्न दूर होते हैं।",
    mantra: "ॐ गं गणपतये नमः। ॐ बगलामुख्यै नमः।",
    location: "Main Gateway Arch",
  },
];
